### ISSUE TITLE
 cannot load such file

### ISSUE THREAD

**Issue by sokrate** [svoboda-jan/asterisk-ari#3]
Hello,

I installed ruby using rvm, tried to create sample application, but got error:
`require': cannot load such file -- asterisk-ari-client (LoadError)

Gem is installed.
Tried on ruby 1.9.3, 2.0.0, 2.2.1

Thanks in advice

**Comment by svoboda-jan** [comment]
Hi,

the correct way to require the gem when not using bundler is `require 'asterisk/ari/client' `.

If you require any further information or assistance please reopen this issue.

**Comment by svoboda-jan** [comment]
I have updated the readme to reflect the correct require path.
