### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by harold-s** [svoboda-jan/asterisk-ari#4]
Hello,

Any ideas how to manage a timeout ? (if the Asterisk server doesn't answer)

Thanks for the gem by the way

**Comment by svoboda-jan** [comment]
Hi,

you can specify timeout when instantiating the client:

```ruby
# instantiate client
@client = Ari::Client.new(
  url: 'http://127.0.0.1:8088/ari',
  api_key: 'asterisk:asterisk',
  app: 'my-app',
  open_timeout: 2,
  read_timeout: 2
)
```
