### ISSUE TITLE
Playing media in asterisk

### ISSUE THREAD

**Issue by kos-zenin** [svoboda-jan/asterisk-ari#5]
Hello, 

Could you please help me to play my own audio file after call start?
Or Maybe asterisk can synthesis text after /channels/:id/play?media='My awesome text' call.

How can I see this functionality:

`      e.channel.on :channel_dtmf_received { |e| e.channel.play(media: "hello world") } `

Any help would be awesome.

**Comment by svoboda-jan** [comment]
Hi,

to play media on a channel you just call the `play` method and pass the `media` option with media's URI to play:

```ruby
channel.play media: "sound:nameOfTheFile"
```

Currently `sound:` and `recording:` URI's are supported. Paths are relative to the configuged sound and recordings paths.

**Comment by kos-zenin** [comment]
Yes, I see, but I ask you about playing text, not file. I can configure asterisk to use festival or any other tts engine. Could you advise how can I use your gem with asterisk+festival to play text?

**Comment by svoboda-jan** [comment]
Asterisk ARI API does not have direct TTS (Text To Speech) support. You could create the file by calling external program and then play it using the `play` method.
