### ISSUE TITLE
originate always pass 'app' as argument to the asterisk

### ISSUE THREAD

**Issue by andrius** [svoboda-jan/asterisk-ari#6]
Hi, I am trying to originate into asterisk dialplan using following command:

```ruby
Ari::Channel.originate client:  $client,
                                endpoint:  'SIP/test-900',
                                callerid:  'TEST',
                                context:   'queues',
                                extension: 'enter',
                                priority:  1,
                                formats:   'g722,slin,gsm'
```

I'm getting following with `ngrep`:

```
 T +0.001207 172.28.0.6:46736 -> xxxxxx:8088 [AP]
POST /ari/channels?client=%23%3CAri%3A%3AClient%3A0x00005578a62e3c08%3E&endpoint=SIP%2Ftest-900&callerid=TEST&context=queues&extension=enter&priority=1&
formats=g722%2Cslin%2Cgsm&api_key=xxxxxx
fbce4&app=test-app HTTP/1.1.
User-Agent: asterisk-ari-client/0.0.8 ruby/2.5.2.
```

and if I originate with `curl`:

```
T +0.010310 172.28.0.6:46876 -> xxxxxxx:8088 [AP]
POST /ari/channels?endpoint=SIP/test-900&formats=g722&&context=queues&extension=enter&priority=1 HTTP/1.1.
User-Agent: curl/7.61.1.
```

I think, issue because of this line and it's global for anything where app is optional argument:

https://github.com/svoboda-jan/asterisk-ari/blob/master/lib/ari/client.rb#L35

**Comment by svoboda-jan** [comment]
Hello, currently we just pass everything available in the options to the HTTP request. We know that not every parameter is required for every request, but due to the the way this gem works it would require a substantial change to the code, which we currently don't see as necessary as it works the way it is.
